name: Deploy to Production

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run final tests
      run: |
        pytest tests/ -v
        
    - name: Build Docker image
      run: |
        docker build -t mlops-app:${{ github.sha }} .
        docker tag mlops-app:${{ github.sha }} mlops-app:latest
        
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Push to Docker Hub
      run: |
        docker tag mlops-app:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/mlops-app:${{ github.sha }}
        docker tag mlops-app:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/mlops-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/mlops-app:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/mlops-app:latest
        
    - name: Trigger Jenkins Job
      run: |
        echo "Triggering Jenkins deployment job..."
        curl -X POST \
          -H "Authorization: Bearer ${{ secrets.JENKINS_TOKEN }}" \
          -H "Content-Type: application/json" \
          "${{ secrets.JENKINS_URL }}/job/mlops-deploy/buildWithParameters" \
          -d '{
            "IMAGE_TAG": "${{ github.sha }}",
            "DOCKER_IMAGE": "${{ secrets.DOCKER_USERNAME }}/mlops-app:${{ github.sha }}"
          }' || echo "Jenkins job trigger failed - continuing..."
          
    - name: Send deployment notification
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "MLOps CI/CD Pipeline - Deployment Successful"
        to: ${{ secrets.ADMIN_EMAIL }}
        from: ${{ secrets.EMAIL_USERNAME }}
        body: |
          Deployment to production has been completed successfully!
          
          Details:
          - Commit: ${{ github.sha }}
          - Branch: ${{ github.ref }}
          - Docker Image: ${{ secrets.DOCKER_USERNAME }}/mlops-app:${{ github.sha }}
          - Timestamp: ${{ github.event.head_commit.timestamp }}
          
          The application is now available in production.
          
          Best regards,
          MLOps CI/CD Pipeline
